### ISSUE TITLE
Doesn't accept any "Channel Name"

### ISSUE THREAD

**Issue by codeandcreate** [Schmiddiii/Tubefeeder#1]
- checked out via git clone
- i compiled with "cargo build --release" on Debian Bullseye/sid.
- app launches without a problem
- tryed differend channel names and channel ids directly copy/paste from youtube.
=> "Could not parse feed of channel. Is .... a valid channel id or name?"

For example: https://www.youtube.com/channel/UCT8fbPYycfhjYzLbsU1dl3Q / "ZDF Comedy"

**Comment by Schmiddiii** [comment]
Yes, I know.
The channel name displayed on the website does not always match the channel name this application needs.
This application needs the channel name, so that `https://www.youtube.com/user/{}` is a valid url.
Such a url can be pretty hard to find (no idea why this seems to exist for some channels but not for others).

I might be able to change it so that it requires a name, so that `https://www.youtube.com/c/{}/featured`  must be valid.
Such a name can be received by clicking `Home` on the channels page (ZDFComedy in your case).

Please note, that the input for `Channel Name` does not accept any channel ids.

When you are not able to find a matching name, you still can add the channel ID to the subscriptions file described [here](https://github.com/Schmiddiii/Tubefeeder/wiki/Subscriptions) (the old way).

**Comment by Schmiddiii** [comment]
Can you try out the new branch `fix-channel-name`. I believe this might fix your problem, but might also break other channels (who knows).

The branch uses the above mentioned url `https://www.youtube.com/c/{}/featured`, so try to get the channel name using the mentioned method of receiving the channel name.

**Comment by codeandcreate** [comment]
i have tryed it... but it doesn't really fix the problem... if i could add successfully the channel ids, it would be much easier just to edit the subscriptions.db and put all channel ids in.

you should really add a function to use the channel-ids just with checking via https://www.youtube.com/feeds/videos.xml?... All ids work if i put it in the subscriptions.db (i have 75 channels in my list).

a little screenshot of your app running on my reform laptop:
![screenshot-2021-04-10-20-51-41](https://user-images.githubusercontent.com/22428204/114281955-98ada280-9a41-11eb-9701-c6d8a1d25974.png)
(changed the font sizes and preview size a little bit for desktop usage)

**Comment by Schmiddiii** [comment]
I'm not sure what you are requesting.
Do you want the input of the subscriptions page to also accept channel ids? 
That would be possible.

**Comment by codeandcreate** [comment]
yeah, for example :) maybe (as future feature) you could add something like a opml import/export

**Comment by Schmiddiii** [comment]
I have implemented, that the subscriptions box now accepts IDs.
Would you mind checking it out?

I did not know about opml yet. 
Might be a feature I will make in the future.  
This will probably be another script like the import from NewPipe.

**Comment by codeandcreate** [comment]
Looks nice 👍🏻  i've tryed with UCT8fbPYycfhjYzLbsU1dl3Q. you should add reading the channels name after adding from https://www.youtube.com/feeds/videos.xml?channel_id=UCT8fbPYycfhjYzLbsU1dl3Q (...)

but its not a big deal ... after refresh it will be displayed anyway

youtube had a channels import/export feature in the past and used opml for this. maybe you could also use it for storing channnels instead of the db-file... if you want i can make an new feature request with more details.

**Comment by Schmiddiii** [comment]
Having the name not displayed immediately is not a big problem I think.
Most people change their subscriptions maybe once in a week, so it is not that important but could be changed in the future.

Having  opml instead of my custom db file would be nice (most crashes I have are from failing to the parsing the db file, because I coded it in a really bad way). But I probably will not work on such a big change in the next time as my university will start soon. Maybe in a few months. But you are open to create a feature request for it.
